create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;
create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;
 



--  postgres://
 
--  pyygaqofyvyxli
 
--  :
 
--  95ceb69e4a27c35b74668c896963fad82991d16ff36de4b2a01f17f729b142e2
 
--  @
 
--  ec2-18-215-111-67.compute-1.amazonaws.com
 
--  :
 
--  5432
 
--  /d7aeo9slefed76